export const books: string[] = [
  'New Spring',
  'The Eye of the World',
  'The Great Hunt',
  'The Dragon Reborn',
  'The Shadow Rising',
  'The Fires of Heaven',
  'Lord of Chaos',
  'A Crown of Swords',
  'Path of Daggers',
  'Winter\'s Heart',
  'Crossroads of Twilight',
  'Knife of Dreams',
  'The Gathering Storm',
  'Towers of Midnight',
  'A Memory of Light'
]

export const chapters: { [book: string]: string[] } = {
  'New Spring': [
  ],
  'The Eye of the World': [
    'Prologue: Ravens',
    'Prologue: Dragonmount',
    '1: An Empty Road',
    '2: Strangers',
    '3: The Peddler',
    '4: The Gleeman',
    '5: Winternight',
    '6: The Westwood',
    '7: Out of the Woods',
    '8: A Place of Safety',
    '9: Tellings of the Wheel',
    '10: Leavetaking',
    '11: The Road to Taren Ferry',
    '12: Across the Taren',
    '13: Choices',
    '14: The Stag and the Lion',
    '15: Strangers and Friends',
    '16: The Wisdom',
    '17: Watchers and Hunters',
    '18: The Caemlyn Road',
    '19: Shadow\'s Waiting',
    '20: Dust on the Wind',
    '21: Listen to the Wind',
    '22: A Path Chosen',
    '23: Wolfbrother',
    '24: Flight Down the Arinelle',
    '25: The Traveling People',
    '26: Whitebridge',
    '27: Shelter From the Storm',
    '28: Footprints in Air',
    '29: Eyes Without Pity',
    '30: Children of Shadow',
    '31: Play for your Supper',
    '32: Four Kings in Shadow',
    '33: The Dark Waits',
    '34: The Last Village',
    '35: Caemlyn',
    '36: Web of the Pattern',
    '37: The Long Chase',
    '38: Rescue',
    '39: Weaving of the Web',
    '40: The Web Tightens',
    '41: Old Friends, and New Threats',
    '42: Remembrance of Dreams',
    '43: Decisions and Apparitions',
    '44: The Dark Along the Ways',
    '45: What Follows in Shadow',
    '46: Fal Dara',
    '47: More Tales of the Wheel',
    '48: The Blight',
    '49: The Dark One Stirs',
    '50: Meetings at the Eye',
    '51: Against the Shadow',
    '52: Neither Beginning Nor End',
    '53: The Wheel Turns'
  ],
  'The Great Hunt': [
    'Prologue: In the Shadow',
    'Chapter 1: The Flame of Tar Valon',
    'Chapter 2: The Welcome',
    'Chapter 3: Friends and Enemies',
    'Chapter 4: Summoned',
    'Chapter 5: The Shadow in Shienar',
    'Chapter 6: Dark Prophecy',
    'Chapter 7: Blood Calls Blood',
    'Chapter 8: The Dragon Reborn',
    'Chapter 9: Leavetakings',
    'Chapter 10: The Hunt Begins',
    'Chapter 11: Glimmers of the Pattern',
    'Chapter 12: Woven in the Pattern',
    'Chapter 13: From Stone to Stone',
    'Chapter 14: Wolfbrother',
    'Chapter 15: Kinslayer',
    'Chapter 16: In the Mirror of Darkness',
    'Chapter 17: Choices',
    'Chapter 18: To the White Tower',
    'Chapter 19: Beneath the Dagger',
    'Chapter 20: Saidin',
    'Chapter 21: The Nine Rings',
    'Chapter 22: Watchers',
    'Chapter 23: The Testing',
    'Chapter 24: New Friends and Old Enemies',
    'Chapter 25: Cairhien',
    'Chapter 26: Discord',
    'Chapter 27: The Shadow in the Night',
    'Chapter 28: A New Thread in the Pattern',
    'Chapter 29: Seanchan',
    'Chapter 30: Daes Dae\'mar',
    'Chapter 31: On the Scent',
    'Chapter 32: Dangerous Words',
    'Chapter 33: A Message From the Dark',
    'Chapter 34: The Wheel Weaves',
    'Chapter 35: Stedding Tsofu',
    'Chapter 36: Among the Elders',
    'Chapter 37: What Might Be',
    'Chapter 38: Practice',
    'Chapter 39: Flight from the White Tower',
    'Chapter 40: Damane',
    'Chapter 41: Disagreements',
    'Chapter 42: Falme',
    'Chapter 43: A Plan',
    'Chapter 44: Five Will Ride Forth',
    'Chapter 45: Blademaster',
    'Chapter 46: To Come Out of the Shadow',
    'Chapter 47: The Grave Is No Bar to My Call',
    'Chapter 48: First Claiming',
    'Chapter 49: What Was Meant to Be',
    'Chapter 50: After'
  ],
  'The Dragon Reborn': [
    'Prologue: Fortress of the Light',
    '1: Waiting',
    '2: Saidin',
    '3: News from the Plain'
  ],
  'The Shadow Rising': [
  ],
  'The Fires of Heaven': [
  ],
  'Lord of Chaos': [
  ],
  'A Crown of Swords': [
  ],
  'Path of Daggers': [
  ],
  'Winter\'s Heart': [
  ],
  'Crossroads of Twilight': [
  ],
  'Knife of Dreams': [
  ],
  'The Gathering Storm': [
  ],
  'Towers of Midnight': [
  ],
  'A Memory of Light': [
  ]
}
